# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: advanced_haml_scaffold_generator 1.0.2 ruby lib

Gem::Specification.new do |s|
  s.name = "advanced_haml_scaffold_generator"
  s.version = "1.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Dmitri Koulikoff"]
  s.date = "2015-02-20"
  s.description = "Extention of the haml generator that generates templates with the use of i18n, cancan and WiceGrid, adds classes to buttons and uses :title helper"
  s.email = "dima@koulikoff.ru"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "advanced_haml_scaffold_generator.gemspec",
    "lib/rails/generators/haml/base.rb",
    "lib/rails/generators/haml/scaffold/scaffold_generator.rb",
    "lib/rails/generators/haml/scaffold/templates/_form.html.haml",
    "lib/rails/generators/haml/scaffold/templates/edit.html.haml",
    "lib/rails/generators/haml/scaffold/templates/index.html.haml",
    "lib/rails/generators/haml/scaffold/templates/layout.html.haml",
    "lib/rails/generators/haml/scaffold/templates/new.html.haml",
    "lib/rails/generators/haml/scaffold/templates/show.html.haml",
    "spec/advanced_haml_scaffold_generator_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/dima4p/advanced_haml_scaffold_generator"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.4.5"
  s.summary = "Extention of the haml generator that is aware of i18n and so forth"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, ["~> 3.1"])
      s.add_development_dependency(%q<rdoc>, ["~> 4.1"])
      s.add_development_dependency(%q<bundler>, ["~> 1.6"])
      s.add_development_dependency(%q<jeweler>, ["~> 2.0"])
      s.add_development_dependency(%q<simplecov>, ["~> 0.0"])
    else
      s.add_dependency(%q<rspec>, ["~> 3.1"])
      s.add_dependency(%q<rdoc>, ["~> 4.1"])
      s.add_dependency(%q<bundler>, ["~> 1.6"])
      s.add_dependency(%q<jeweler>, ["~> 2.0"])
      s.add_dependency(%q<simplecov>, ["~> 0.0"])
    end
  else
    s.add_dependency(%q<rspec>, ["~> 3.1"])
    s.add_dependency(%q<rdoc>, ["~> 4.1"])
    s.add_dependency(%q<bundler>, ["~> 1.6"])
    s.add_dependency(%q<jeweler>, ["~> 2.0"])
    s.add_dependency(%q<simplecov>, ["~> 0.0"])
  end
end

