# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: advanced_haml_scaffold_generator 2.2.1 ruby lib

Gem::Specification.new do |s|
  s.name = "advanced_haml_scaffold_generator".freeze
  s.version = "2.2.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Dmitri Koulikoff".freeze]
  s.date = "2020-06-17"
  s.description = "Extention of the haml generator that generates templates with the use of i18n, cancan and WiceGrid, adds classes to buttons and uses :title helper".freeze
  s.email = "dima@koulikoff.ru".freeze
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "advanced_haml_scaffold_generator.gemspec",
    "lib/rails/generators/haml/base.rb",
    "lib/rails/generators/haml/scaffold/scaffold_generator.rb",
    "lib/rails/generators/haml/scaffold/templates/_form.html.haml",
    "lib/rails/generators/haml/scaffold/templates/destroy.js.coffee",
    "lib/rails/generators/haml/scaffold/templates/edit.html.haml",
    "lib/rails/generators/haml/scaffold/templates/index.html.haml",
    "lib/rails/generators/haml/scaffold/templates/layout.html.haml",
    "lib/rails/generators/haml/scaffold/templates/new.html.haml",
    "lib/rails/generators/haml/scaffold/templates/show.html.haml",
    "spec/advanced_haml_scaffold_generator_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/dima4p/advanced_haml_scaffold_generator".freeze
  s.licenses = ["MIT".freeze]
  s.rubygems_version = "3.1.2".freeze
  s.summary = "Extention of the haml generator that is aware of i18n and so forth".freeze

  if s.respond_to? :specification_version then
    s.specification_version = 4
  end

  if s.respond_to? :add_runtime_dependency then
    s.add_development_dependency(%q<rspec>.freeze, ["~> 3.1"])
    s.add_development_dependency(%q<rdoc>.freeze, ["~> 4.1"])
    s.add_development_dependency(%q<bundler>.freeze, ["~> 1.6"])
    s.add_development_dependency(%q<jeweler>.freeze, ["~> 2.0"])
    s.add_development_dependency(%q<simplecov>.freeze, ["~> 0.0"])
  else
    s.add_dependency(%q<rspec>.freeze, ["~> 3.1"])
    s.add_dependency(%q<rdoc>.freeze, ["~> 4.1"])
    s.add_dependency(%q<bundler>.freeze, ["~> 1.6"])
    s.add_dependency(%q<jeweler>.freeze, ["~> 2.0"])
    s.add_dependency(%q<simplecov>.freeze, ["~> 0.0"])
  end
end

